### ISSUE TITLE
duplicate value for resource 'attr/strokeWidth'

### ISSUE THREAD

**Issue by wiemrh** [afreakyelf/HorizontalCalendarLibrary#1]
24:25: AAPT: error: duplicate value for resource 'attr/strokeWidth' with config ''.
with  v0.1.3

**Comment by afreakyelf** [comment]
Hi, Thanks for checking out my code. I have fixed the bug and released a new build as well. Please raise issue if you still face. Thank You
Don't forget to star XD

**Comment by manishakalia** [comment]
24:25: AAPT: error: duplicate value for resource 'attr/strokeWidth' with config 
Same issue I am facing in latest release
